### ISSUE TITLE
Why though?

### ISSUE THREAD

**Issue by awnumar** [moige/BiCrypt#3]
What's the point of encrypting something twice with AES? Once is more than secure enough, and if you want a higher security margin than AES256 provides, use something like XChaCha20Poly1305. Double-AES is completely unnecessary, not to mention needlessly slow.

If you want the entropy of two user passwords, you could XOR the outputs of your key-derivation function together and use that as the key. Then again, you're using SHA256 as a KDF, so that would need to be upgraded to something like Scrypt, or at least PBKDF2.

**Comment by phlogisto** [comment]
Also only half of the file is encrypted with each AES (odd bytes with one, even bytes with the other one). If I could get hold of one key, I would still be able to decrypt half of the file. Use case for this is really not clear.

**Comment by awnumar** [comment]
@phlogisto Oh damn. Yeah, that's a _lot_ worse than double-AES.

**Comment by moige** [comment]
This is a learning project. I already explained in the original [reddit](https://www.reddit.com/r/Python/comments/77tuu7/bicrypt_encrypt_files_with_two_differents/) post. I only want reviews, advices o whatever that help me to improve my self.

**Comment by awnumar** [comment]
Then you should make that clear in **bold** on your readme so that someone doesn't come along and use this code to store something important.

**Comment by moige** [comment]
@awnumar Readme already have a declaration about that... So clear in **bold**

**Comment by awnumar** [comment]
@moige That's not really good enough. You should make clear that this is a learning exercise for you and as such should be on a different planet than any production code.

**Comment by awnumar** [comment]
👍
